### ISSUE TITLE
What's the browser default?

### ISSUE THREAD

**Issue by mystiquewolf** [Cimbali/toggle-dark-mode#1]
I mean the way Firefox behaves without the addon? I guess it's to follow the system default, am I right? Not sure if the addon restores it upon uninstall, didn't bother to check, but decided to open this issue just in any case.

**Comment by Cimbali** [comment]
I think the default is to inherit from the browser theme, which in turn may or may not inherit from the system theme.

Since this add-on is onl toggling a system preference without doing anything else, uninstalling does no changes to the preference, which means leaving it in its last state.

Determining which correct default to reset after uninstalling is not trivial I guess, maybe the previous value could be stored somewher? .

**Comment by mystiquewolf** [comment]
I think the value that this setting is set to upon a clear installation of Firefox / clean profile. I don't know if by default Firefox looks at the browser theme or at the device theme.

**Comment by Cimbali** [comment]
It seems currently the default is [to inherit from the system](https://github.com/bolucat/Firefox/blob/f05583bdadf1a12360e3088ed892ee486005683e/modules/libpref/init/StaticPrefList.yaml#L1305-L1315), not the browser.

**Comment by mystiquewolf** [comment]
FWIW i found [THIS](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/types/BrowserSetting/clear)... Seems legit.

**Comment by Cimbali** [comment]
Thanks! It seems from [the `BrowsetSetting.set()` docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/types/BrowserSetting/set) that `BrowserSetting.clear()` is called upon uninstall, as we the add-on releases control of the preference.
