### ISSUE TITLE
Request: add per-site toggle

### ISSUE THREAD

**Issue by CogentRedTester** [Cimbali/toggle-dark-mode#5]
Some sites have better dark than light themes and vice versa. It would be really cool if we could set which mode we prefer for a specific site and for the extension to remember it.

**Comment by Cimbali** [comment]
Sorry but this is not possible, because the light/dark setting we toggle is browser-wide. You’d have to find another add-on that uses a different mechanism to toggle light/dark modes, e.g. by injecting their own css.

Also this would require the add-on to monitor every site you’re on, to figure out whether to toggle color for the tab or not, and that’s both a lot of work and a lot of permissions.

**Comment by CogentRedTester** [comment]
No worries, thanks for getting back to me quickly. 😢
