### ISSUE TITLE
Doesn't work on Gmail

### ISSUE THREAD

**Issue by quicksite** [Cimbali/toggle-dark-mode#9]
Is there some kind of instruction I have to give to the extension to specify on which sites I want it to be enabled?

**Comment by Cimbali** [comment]
The add-on toggles a browser setting, that’s all it does. Individual websites then receive that preference and display the correct theme, if they support it. Sometimes, you first have to select the option in the website appearance preferences to use something like “system colours” (or something along those lines) so it knows to honour your dark/light preference rather than ignore it.

I find for google search pages I have to refresh once or twice, maybe ignoring cache (Ctrl+F5) after toggling the scheme, maybe it is the same on gmail? I don’t use gmail unfortunately so can’t be of more help.

**Comment by quicksite** [comment]
thank you!
